apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-s3
  # namespace: external-secrets
spec:
  refreshInterval: "5s" # Это определяет интервал времени, через который External Secret контроллер будет обновлять секретные данные.
  secretStoreRef: # Этот объект содержит ссылку на Secret Store Vault, которое будет использоваться.
    name: vault-backend-s3
    kind: ClusterSecretStore
  target: # Это указывает целевой секрет Kubernetes, который будет создан External Secret.
    name: s3-secret # Имя секрета Kubernetes, который будет создан.
    creationPolicy: Owner # В этом случае External Secret будет выступать в качестве владельца целевого секрета Kubernetes.
  data: # Это массив секретных пар ключ-значение, которые External Secret извлечет из Secret Store Vault и сохранит в Kubernetes secret.
    - secretKey: PG_HOST # Это указывает имя ключа для секретного значения в секрете Kubernetes.
      remoteRef: # Это объект, содержащий ссылку на секрет в Secret Store Vault.
        key: secret/data/s3 # Это указывает путь к секрету в Secret Store Vault. Прописываем из вывода `vault kv put secret/postgres`.
        property: PG_HOST # Здесь указывается имя секретного свойства (имя секретного значения), которое необходимо извлечь из секрета Vault.
    - secretKey: PG_PASSWORD
      remoteRef:
        key: secret/data/s3
        property: PG_PASSWORD
    - secretKey: PG_USER
      remoteRef:
        key: secret/data/s3
        property: PG_USER
    - secretKey: PG_DATABASE # Это указывает имя ключа для секретного значения в секрете Kubernetes.
      remoteRef: # Это объект, содержащий ссылку на секрет в Secret Store Vault.
        key: secret/data/s3 # Это указывает путь к секрету в Secret Store Vault. Прописываем из вывода `vault kv put secret/postgres`.
        property: PG_DATABASE # Здесь указывается имя секретного свойства (имя секретного значения), которое необходимо извлечь из секрета Vault.
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/data/s3
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/data/s3
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_BUCKET_NAME # Это указывает имя ключа для секретного значения в секрете Kubernetes.
      remoteRef: # Это объект, содержащий ссылку на секрет в Secret Store Vault.
        key: secret/data/s3 # Это указывает путь к секрету в Secret Store Vault. Прописываем из вывода `vault kv put secret/postgres`.
        property: AWS_BUCKET_NAME # Здесь указывается имя секретного свойства (имя секретного значения), которое необходимо извлечь из секрета Vault.
    - secretKey: AWS_HOST
      remoteRef:
        key: secret/data/s3
        property: AWS_HOST
    - secretKey: AWS_PORT
      remoteRef:
        key: secret/data/s3
        property: AWS_PORT