apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-api
  # namespace: external-secrets
spec:
  refreshInterval: "5s" # Это определяет интервал времени, через который External Secret контроллер будет обновлять секретные данные.
  secretStoreRef: # Этот объект содержит ссылку на Secret Store Vault, которое будет использоваться.
    name: vault-backend-api
    kind: ClusterSecretStore
  target: # Это указывает целевой секрет Kubernetes, который будет создан External Secret.
    name: api-secret # Имя секрета Kubernetes, который будет создан.
    creationPolicy: Owner # В этом случае External Secret будет выступать в качестве владельца целевого секрета Kubernetes.
  data: # Это массив секретных пар ключ-значение, которые External Secret извлечет из Secret Store Vault и сохранит в Kubernetes secret.
    - secretKey: DB_PORT # Это указывает имя ключа для секретного значения в секрете Kubernetes.
      remoteRef: # Это объект, содержащий ссылку на секрет в Secret Store Vault.
        key: secret/data/api # Это указывает путь к секрету в Secret Store Vault. Прописываем из вывода `vault kv put secret/postgres`.
        property: DB_PORT # Здесь указывается имя секретного свойства (имя секретного значения), которое необходимо извлечь из секрета Vault.
    - secretKey: DB_HOST
      remoteRef:
        key: secret/data/api
        property: DB_HOST
    - secretKey: CLIENT_URL
      remoteRef:
        key: secret/data/api
        property: CLIENT_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/data/api
        property: REDIS_URL