apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-s3
spec:
  provider:
    vault:
      server: "{{ .Values.vault.server_ip }}" # Указываем адрес Hashicorp Vault.
      path: "secret" # Только по этому пути может ходить ClusterSecretStore в Hashicorp Vault.
      version: "v2"
      auth:
        # AppRole аутентифицируется в Vault с помощью механизма
        # аутентификации AppRole https://www.vaultproject.io/docs/auth/approle.
        appRole:
          # Путь, по которому подключен сервер аутентификации AppRole.
          path: "approle"
          # Идентификатор роли, настроенный в серверной части проверки подлинности AppRole.
          roleId: "{{ .Values.vault.all_role_id }}" # Значение берем из  вывода `terraform output role_id`.
          secretRef:
            name: "vault-secret-s3" # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
            key: "secret-id" # Секретный идентификатор AppRole.
            # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.