pgdumper:
  name: pg-dumper
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgdumper
  version: 60
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT
pgrestore:
  name: pg-restore
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgrestore
  version: 15
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT
app:
  name: inf-app
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-frontend-dev
  version: "104"
  components: frontend
  port: 3000
  replicas: 1
  requests:
    cpu: "250m"
    memory: "250Mi"
  limits:
    cpu: "250m"
    memory: "250Mi"
  envs:
    - EXTERNAL_CATALOG_SERVER_URL
    - API_SERVER_URL
api:
  name: inf-api
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-backend-dev
  version: "7"
  components: backend
  port: 2348
  replicas: 1
  requests:
    cpu: "500m"
    memory: "350Mi"
  limits:
    cpu: "500m"
    memory: "350Mi"
  envs:
    - CLIENT_URL
    - DB_PORT
    - DB_HOST
    - REDIS_URL
postgres:
  name: postgres
  image: postgres
  version: 14
  replicas: 1
  components: postgres
  port: 5432
  requests:
    cpu: "1000m"
    memory: "2000Mi"
  limits:
    cpu: "1000m"
    memory: "2000Mi"
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
redis:
  name: redis
  image: redis
  version: 7.0.7
  replicas: 1
  components: redis
  port: 6379
  requests:
    cpu: "200m"
    memory: "250Mi"
  limits:
    cpu: "200m"
    memory: "250Mi"
database:
  db: inf
  user: postgres
  password: postgres
vault:
  secret_id_app: "a584c349-bc7c-6799-4fe1-aa47dccd93cd"
  secret_id_api: "2f0ccaff-7905-b2fc-267c-33e3f3794670"
  secret_id_postgres: "e03c3021-22ad-39a2-a48a-167255eef5ef"
  secret_id_s3: "4e045eb9-7a73-6b3b-834c-25c7720b7124"
  all_role_id: "c756d6ca-a872-1e74-c1fd-ccf21fd5dec1"
  server_ip: "http://10.96.201.220:8200"
