pgdumper:
  name: pg-dumper
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgdumper
  version: 60
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT
pgrestore:
  name: pg-restore
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgrestore
  version: 15
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT
app:
  name: inf-app
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-frontend-dev
  version: "42"
  components: frontend
  port: 3000
  replicas: 1
  requests:
    cpu: "250m"
    memory: "250Mi"
  limits:
    cpu: "250m"
    memory: "250Mi"
  envs:
    - EXTERNAL_CATALOG_SERVER_URL
    - API_SERVER_URL
api:
  name: inf-api
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-backend-dev
  version: "7"
  components: backend
  port: 2348
  replicas: 1
  requests:
    cpu: "500m"
    memory: "350Mi"
  limits:
    cpu: "500m"
    memory: "350Mi"
  envs:
    - CLIENT_URL
    - DB_PORT
    - DB_HOST
    - REDIS_URL
postgres:
  name: postgres
  image: postgres
  version: 14
  replicas: 1
  components: postgres
  port: 5432
  requests:
    cpu: "1000m"
    memory: "2000Mi"
  limits:
    cpu: "1000m"
    memory: "2000Mi"
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
redis:
  name: redis
  image: redis
  version: 7.0.7
  replicas: 1
  components: redis
  port: 6379
  requests:
    cpu: "200m"
    memory: "250Mi"
  limits:
    cpu: "200m"
    memory: "250Mi"
database:
  db: inf
  user: postgres
  password: postgres
vault:
  secret_id_app: "c37c31b6-a3e5-ffd9-6627-91130943f523"
  secret_id_api: "210ffe12-c040-4106-07ce-87ed94e8de41"
  secret_id_postgres: "558666c2-0d3b-4b02-4bcf-af6306d78505"
  secret_id_s3: "c211490e-7804-bcf9-bad0-693ea7c39144"
  all_role_id: "eeba316e-efc1-c7fd-8430-b6f03fcb694d"
  server_ip: "http://10.96.218.194:8200"