apiVersion: v1
stringData:
  secret-id: "{{ .Values.vault.secret_id_app }}" # Значение берем из  вывода `terraform output secret_id`.
kind: Secret
metadata:
  name: vault-secret-app # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
  # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.
type: Opaque